export type StreamId =
  | 'Billboard'
  | 'Category'
  | 'Size'
  | 'Customer'
  | 'Order'
  | 'Product'
  | 'Image'
  | 'Store'
  | 'Variant';
export type EventType =
  | 'BillboardRegistered'
  | 'BillboardRemoved'
  | 'CategoryRegistered'
  | 'CategoryRemoved'
  | 'SizeRegistered'
  | 'SizeRemoved'
  | 'CustomerRegistered'
  | 'CustomerRemoved'
  | 'ImageRegistered'
  | 'ImageRemoved'
  | 'ProductRegistered'
  | 'ProductRemoved'
  | 'StoreRegistered'
  | 'StoreRemoved'
  | 'VariantRegistered'
  | 'VariantRemoved';
